# Generated by Django 5.0.2 on 2024-05-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_book_rentel_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
